(()=>{"use strict";
const SIZE=8,CFG_KEY="ppb_admin_config_v1",STORE_KEY="ppb_premium_state_v2";
const DEFAULT_ICONS=[
{id:"tomato",name:"Томат",kind:"emoji",value:"🍅"},{id:"broccoli",name:"Брокколи",kind:"emoji",value:"🥦"},{id:"egg",name:"Яйцо",kind:"emoji",value:"🍳"},{id:"chicken",name:"Курица",kind:"emoji",value:"🍗"},{id:"lettuce",name:"Салат",kind:"emoji",value:"🥬"},{id:"rice",name:"Рис",kind:"emoji",value:"🍚"},{id:"avocado",name:"Авокадо",kind:"emoji",value:"🥑"},{id:"cucumber",name:"Огурец",kind:"emoji",value:"🥒"}
];
const DEFAULT_CFG={season:{name:"PP Challenge",subtitle:"Полезный сезон PP Balance",target:48560,moves:22,active:true},prizes:[],icons:DEFAULT_ICONS};
const $=id=>document.getElementById(id),$$=q=>[...document.querySelectorAll(q)],sleep=ms=>new Promise(r=>setTimeout(r,ms));
const escapeHtml=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function loadCfg(){try{const v=JSON.parse(localStorage.getItem(CFG_KEY)||"null");if(v?.season&&Array.isArray(v.icons)&&v.icons.length>=6)return v}catch{}return structuredClone(DEFAULT_CFG)}
function loadState(){const base={coins:12560,gems:35,lives:5,level:24,score:0,best:0,games:0,collected:0,stars:{20:3,21:3,22:2,23:3},inventory:{shuffle:3,bomb:2,salad:3,extra:2},dailyDay:3,dailyClaim:"",sound:true,haptic:true};try{return Object.assign(base,JSON.parse(localStorage.getItem(STORE_KEY)||"{}"))}catch{return base}}
let cfg=loadCfg(),icons=cfg.icons?.length>=6?cfg.icons:DEFAULT_ICONS,iconMap=new Map(icons.map(x=>[x.id,x]));
let state=loadState(),board=[],selected=null,busy=false,boosterMode="",moves=22,score=0,goals={},levelPlaying=state.level;
const tg=window.Telegram?.WebApp,fx=$("fxLayer"),boardEl=$("board"),frame=$("gameFrame");
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state))}
function viewport(){const h=tg?.viewportStableHeight||tg?.viewportHeight||window.visualViewport?.height||innerHeight;document.documentElement.style.setProperty("--app-h",Math.round(h)+"px")}
try{tg?.ready();tg?.expand();tg?.requestFullscreen?.();tg?.setHeaderColor?.("#020402");tg?.setBackgroundColor?.("#020402");tg?.onEvent?.("viewportChanged",viewport)}catch{}
viewport();addEventListener("resize",viewport);window.visualViewport?.addEventListener("resize",viewport);
function haptic(kind="light"){if(!state.haptic)return;try{tg?.HapticFeedback?.impactOccurred(kind)}catch{}}
let audioCtx=null;function beep(freq=520,dur=.06){if(!state.sound)return;try{audioCtx||=new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;o.type="sine";g.gain.setValueAtTime(.05,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch{}}
function toast(text){const el=$("toast");el.textContent=text;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),1600)}
const format=n=>Number(n||0).toLocaleString("ru-RU");
function syncTop(){for(const id of["coinsTop","coinsShop"])if($(id))$(id).textContent=format(state.coins);$("gemsTop").textContent=format(state.gems);$("livesTop").textContent=`${state.lives}/5`;$("levelTop").textContent=state.level;$("profileBest").textContent=format(state.best);$("profileGames").textContent=state.games;$("profileCollected").textContent=format(state.collected);$("profileLevel").textContent=state.level;save()}
function iconHtml(type,cls="food"){const i=iconMap.get(type);if(!i)return `<span class="${cls}">❔</span>`;return i.kind==="image"?`<img class="${cls}" src="${i.value}" alt="${escapeHtml(i.name)}">`:`<span class="${cls}">${escapeHtml(i.value)}</span>`}
function randType(){return icons[Math.floor(Math.random()*icons.length)].id}
function makeTile(type,special=""){return{type,special,id:(globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2))}}
function showScreen(id){$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id));$$(".bottom-nav button").forEach(x=>x.classList.toggle("active",x.dataset.screen===id));if(id==="map")renderMap();if(id==="tournament")renderTournament();if(id==="shop")renderShop();if(id==="profile")syncTop();viewport()}
$$(".bottom-nav button").forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));
function openModal(id){$(id).classList.add("open")}function closeModal(id){$(id).classList.remove("open")}
$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
$("settingsBtn").onclick=()=>openModal("settingsModal");
$("soundToggle").onclick=()=>{state.sound=!state.sound;$("soundToggle").classList.toggle("on",state.sound);save();beep(650)};
$("hapticToggle").onclick=()=>{state.haptic=!state.haptic;$("hapticToggle").classList.toggle("on",state.haptic);save();haptic("medium")};
$("soundToggle").classList.toggle("on",state.sound);$("hapticToggle").classList.toggle("on",state.haptic);
function renderMap(){const season=cfg.season||DEFAULT_CFG.season;$("mapSeason").textContent=season.name||"PP Challenge";const pts=[[15,68],[31,54],[48,64],[64,46],[76,31],[58,19],[29,25],[20,42]],start=Math.max(1,state.level-4),levels=Array.from({length:8},(_,i)=>start+i);$("levelNodes").innerHTML=levels.map((lv,i)=>{const locked=lv>state.level,current=lv===state.level,stars=state.stars[lv]||0;return `<button class="level-node ${locked?"locked":current?"current":"open"}" data-level="${lv}" data-stars="${stars?"★".repeat(stars):locked?"":"☆☆☆"}" style="left:${pts[i][0]}%;top:${pts[i][1]}%"><span>${lv}</span></button>`}).join("");$$("#levelNodes .level-node").forEach(n=>n.onclick=()=>{if(n.classList.contains("locked"))return toast("Сначала пройдите предыдущий уровень");startLevel(Number(n.dataset.level))});$("mapCurrent").textContent=`Уровень ${state.level}`;$("mapHint").textContent="Соберите цели и заработайте 3 звезды"}
$("playCurrent").onclick=()=>startLevel(state.level);$("dailyOpen").onclick=()=>{renderDaily();showScreen("daily")};
function levelRules(lv){const pool=icons.map(x=>x.id),a=pool[(lv*2)%pool.length],b=pool[(lv*2+1)%pool.length],c=pool[(lv*2+3)%pool.length],base=8+(lv%5)*2;return{moves:Math.max(16,Number(cfg.season?.moves)||22),targets:{[a]:base,[b]:base,[c]:base},scoreTarget:Math.max(6500,Math.round((Number(cfg.season?.target)||48560)*(.72+((lv%4)*.08))))}}
function createsMatchAt(b,r,c,t){return(c>1&&b[r][c-1]?.type===t&&b[r][c-2]?.type===t)||(r>1&&b[r-1][c]?.type===t&&b[r-2][c]?.type===t)}
function generateBoard(){board=Array.from({length:SIZE},()=>Array(SIZE));for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){let t,g=0;do{t=randType();g++}while(createsMatchAt(board,r,c,t)&&g<50);board[r][c]=makeTile(t)}if(!hasMove())generateBoard()}
function renderGoals(){$("goalBox").innerHTML=Object.entries(goals).map(([t,g])=>`<div class="goal ${g.left<=0?"done":""}">${iconHtml(t,"mini-food")}<b>${Math.max(0,g.left)}</b></div>`).join("")}
function startLevel(lv){if(state.lives<=0)return toast("Жизни закончились");levelPlaying=lv;const rules=levelRules(lv);moves=rules.moves;score=0;goals={};for(const[t,n]of Object.entries(rules.targets))goals[t]={target:n,left:n};selected=null;busy=false;boosterMode="";generateBoard();renderBoard(true);renderGoals();$("moves").textContent=moves;$("score").textContent="0";$("gameLevel").textContent=lv;$("gameMessage").textContent="Соберите полезные продукты";showScreen("game");setTimeout(()=>{try{tg?.requestFullscreen?.()}catch{}},100)}
function renderBoard(drop=false){boardEl.innerHTML="";for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){const t=board[r][c],b=document.createElement("button");b.className=`tile ${t.special?`special-${t.special}`:""} ${drop?"drop":""}`;b.dataset.r=r;b.dataset.c=c;b.innerHTML=iconHtml(t.type);if(selected&&selected.r===r&&selected.c===c)b.classList.add("selected");b.onclick=()=>tileClick(r,c,b);boardEl.appendChild(b)}$("moves").textContent=moves;$("score").textContent=format(score);renderGoals();renderBoosters()}
function renderBoosters(){for(const k of["shuffle","bomb","salad","extra"]){$(`${k}Count`).textContent=state.inventory[k]||0;$(`${k}Btn`).classList.toggle("active",boosterMode===k)}}
const adjacent=(a,b)=>Math.abs(a.r-b.r)+Math.abs(a.c-b.c)===1;
function swapCells(a,b){const t=board[a.r][a.c];board[a.r][a.c]=board[b.r][b.c];board[b.r][b.c]=t}
function animateSwap(a,b){const e1=boardEl.querySelector(`[data-r="${a.r}"][data-c="${a.c}"]`),e2=boardEl.querySelector(`[data-r="${b.r}"][data-c="${b.c}"]`);if(!e1||!e2)return Promise.resolve();const x1=e1.getBoundingClientRect(),x2=e2.getBoundingClientRect(),dx=x2.left-x1.left,dy=x2.top-x1.top;const a1=e1.animate([{transform:"translate(0,0)"},{transform:`translate(${dx}px,${dy}px)`}],{duration:150,easing:"ease-in-out"}),a2=e2.animate([{transform:"translate(0,0)"},{transform:`translate(${-dx}px,${-dy}px)`}],{duration:150,easing:"ease-in-out"});return Promise.all([a1.finished.catch(()=>{}),a2.finished.catch(()=>{})])}
function scanMatches(){const groups=[],matched=new Set(),hCells=new Set(),vCells=new Set();for(let r=0;r<SIZE;r++){let s=0;for(let c=1;c<=SIZE;c++){if(c<SIZE&&board[r][c].type===board[r][s].type)continue;const len=c-s;if(len>=3){const cells=[];for(let x=s;x<c;x++){const k=`${r}:${x}`;cells.push({r,c:x});matched.add(k);hCells.add(k)}groups.push({dir:"row",cells,type:board[r][s].type})}s=c}}for(let c=0;c<SIZE;c++){let s=0;for(let r=1;r<=SIZE;r++){if(r<SIZE&&board[r][c].type===board[s][c].type)continue;const len=r-s;if(len>=3){const cells=[];for(let x=s;x<r;x++){const k=`${x}:${c}`;cells.push({r:x,c});matched.add(k);vCells.add(k)}groups.push({dir:"col",cells,type:board[s][c].type})}s=r}}const intersections=[...matched].filter(k=>hCells.has(k)&&vCells.has(k)).map(k=>{const[r,c]=k.split(":").map(Number);return{r,c}});return{groups,matched,intersections}}
function expandSpecials(clear,triggerType=null){let changed=true;while(changed){changed=false;for(const k of[...clear]){const[r,c]=k.split(":").map(Number),t=board[r]?.[c];if(!t?.special)continue;if(t.special==="row")for(let x=0;x<SIZE;x++){const q=`${r}:${x}`;if(!clear.has(q)){clear.add(q);changed=true}}if(t.special==="col")for(let x=0;x<SIZE;x++){const q=`${x}:${c}`;if(!clear.has(q)){clear.add(q);changed=true}}if(t.special==="bomb")for(let rr=Math.max(0,r-1);rr<=Math.min(SIZE-1,r+1);rr++)for(let cc=Math.max(0,c-1);cc<=Math.min(SIZE-1,c+1);cc++){const q=`${rr}:${cc}`;if(!clear.has(q)){clear.add(q);changed=true}}if(t.special==="rainbow"){const type=triggerType||icons[Math.floor(Math.random()*icons.length)].id;for(let rr=0;rr<SIZE;rr++)for(let cc=0;cc<SIZE;cc++)if(board[rr][cc].type===type){const q=`${rr}:${cc}`;if(!clear.has(q)){clear.add(q);changed=true}}}}}return clear}
async function tileClick(r,c,el){if(busy||moves<=0)return;if(boosterMode==="bomb"){if(!(state.inventory.bomb>0))return;state.inventory.bomb--;boosterMode="";busy=true;const clear=new Set;for(let rr=Math.max(0,r-1);rr<=Math.min(SIZE-1,r+1);rr++)for(let cc=Math.max(0,c-1);cc<=Math.min(SIZE-1,c+1);cc++)clear.add(`${rr}:${cc}`);await clearCells(clear,1);await cascades(2);busy=false;save();checkEnd();return}if(boosterMode==="salad"){if(!(state.inventory.salad>0))return;state.inventory.salad--;boosterMode="";busy=true;const type=board[r][c].type,clear=new Set;for(let rr=0;rr<SIZE;rr++)for(let cc=0;cc<SIZE;cc++)if(board[rr][cc].type===type)clear.add(`${rr}:${cc}`);await clearCells(clear,1);await cascades(2);busy=false;save();checkEnd();return}const p={r,c};if(!selected){selected=p;haptic();renderBoard();return}if(selected.r===r&&selected.c===c){selected=null;renderBoard();return}if(!adjacent(selected,p)){selected=p;renderBoard();return}busy=true;const a=selected,b=p;selected=null;await animateSwap(a,b);const tA=board[a.r][a.c],tB=board[b.r][b.c];swapCells(a,b);renderBoard();let scan=scanMatches();if(tA.special==="rainbow"||tB.special==="rainbow"){moves--;const rainbowPos=tA.special==="rainbow"?b:a,other=tA.special==="rainbow"?tB.type:tA.type,clear=new Set([`${rainbowPos.r}:${rainbowPos.c}`]);expandSpecials(clear,other);for(let rr=0;rr<SIZE;rr++)for(let cc=0;cc<SIZE;cc++)if(board[rr][cc].type===other)clear.add(`${rr}:${cc}`);await clearCells(clear,1);await cascades(2)}else if(!scan.matched.size){swapCells(a,b);renderBoard();el?.classList.add("invalid");$("gameMessage").textContent="Нужна комбинация из 3";haptic("rigid");beep(180,.08);await sleep(260)}else{moves--;await resolveScan(scan,b,1);await cascades(2)}busy=false;save();checkEnd()}
function chooseSpecial(scan,preferred){let kind="",pos=null;if(scan.intersections.length){kind="bomb";pos=scan.intersections.find(x=>x.r===preferred.r&&x.c===preferred.c)||scan.intersections[0]}else{const five=scan.groups.find(g=>g.cells.length>=5),four=scan.groups.find(g=>g.cells.length===4);if(five){kind="rainbow";pos=five.cells.find(x=>x.r===preferred.r&&x.c===preferred.c)||five.cells[Math.floor(five.cells.length/2)]}else if(four){kind=four.dir;pos=four.cells.find(x=>x.r===preferred.r&&x.c===preferred.c)||four.cells[Math.floor(four.cells.length/2)]}}return{kind,pos}}
async function resolveScan(scan,preferred,multi){const spec=chooseSpecial(scan,preferred),clear=new Set(scan.matched);if(spec.pos)clear.delete(`${spec.pos.r}:${spec.pos.c}`);expandSpecials(clear);await clearCells(clear,multi);if(spec.pos){board[spec.pos.r][spec.pos.c]=makeTile(scan.groups[0]?.type||randType(),spec.kind);renderBoard(true);boardEl.querySelector(`[data-r="${spec.pos.r}"][data-c="${spec.pos.c}"]`)?.classList.add("glow");beep(780,.1)}}
async function cascades(multi=2){let scan=scanMatches(),m=multi;while(scan.matched.size){await sleep(120);await resolveScan(scan,scan.groups[0].cells[0],m);$("gameMessage").textContent=`КОМБО ×${m}!`;beep(520+m*75,.08);m++;scan=scanMatches()}if(!hasMove()){generateBoard();renderBoard(true);toast("Нет ходов — поле перемешано")}}
async function clearCells(clear,multi){expandSpecials(clear);const cells=[...clear],gained=cells.length*100*multi;for(const k of cells){const[r,c]=k.split(":").map(Number),e=boardEl.querySelector(`[data-r="${r}"][data-c="${c}"]`);e?.classList.add("pop");burstAt(e);const t=board[r][c];if(goals[t.type])goals[t.type].left--;state.collected++}score+=gained;state.score=score;$("score").textContent=format(score);scoreFly(`+${format(gained)}`);haptic(multi>1?"heavy":"medium");beep(420+multi*70,.06);await sleep(230);for(const k of cells){const[r,c]=k.split(":").map(Number);board[r][c]=null}collapse();renderBoard(true);frame.classList.add("shake");setTimeout(()=>frame.classList.remove("shake"),260);await sleep(220)}
function collapse(){for(let c=0;c<SIZE;c++){const vals=[];for(let r=SIZE-1;r>=0;r--)if(board[r][c])vals.push(board[r][c]);for(let r=SIZE-1,i=0;r>=0;r--,i++)board[r][c]=vals[i]||makeTile(randType())}}
function burstAt(el){if(!el)return;const b=el.getBoundingClientRect(),p=fx.getBoundingClientRect(),x=b.left-p.left+b.width/2,y=b.top-p.top+b.height/2;for(let i=0;i<7;i++){const d=document.createElement("i");d.className="particle";d.style.left=x+"px";d.style.top=y+"px";const a=Math.PI*2*i/7,dist=25+Math.random()*32;d.style.setProperty("--dx",Math.cos(a)*dist+"px");d.style.setProperty("--dy",Math.sin(a)*dist+"px");fx.appendChild(d);setTimeout(()=>d.remove(),700)}}
function scoreFly(txt){const d=document.createElement("b");d.className="score-fly";d.textContent=txt;d.style.left="50%";d.style.top="42%";d.style.transform="translateX(-50%)";fx.appendChild(d);setTimeout(()=>d.remove(),850)}
function hasMove(){for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++)for(const[dr,dc]of[[0,1],[1,0]]){const rr=r+dr,cc=c+dc;if(rr>=SIZE||cc>=SIZE)continue;swapCells({r,c},{r:rr,c:cc});const ok=scanMatches().matched.size>0;swapCells({r,c},{r:rr,c:cc});if(ok)return true}return false}
function checkEnd(){renderBoard();const goalsDone=Object.values(goals).every(g=>g.left<=0);if(goalsDone||score>=levelRules(levelPlaying).scoreTarget)return finish(true);if(moves<=0)return finish(false)}
function starsFor(){const ratio=score/levelRules(levelPlaying).scoreTarget;return ratio>=1.45?3:ratio>=1.15?2:1}
function finish(win){busy=true;state.games++;state.best=Math.max(state.best,score);if(win){const stars=starsFor();state.stars[levelPlaying]=Math.max(state.stars[levelPlaying]||0,stars);state.coins+=250;state.gems+=stars===3?2:1;if(levelPlaying>=state.level)state.level=levelPlaying+1;$("resultTitle").textContent="ПРОЙДЕН!";$("resultScore").textContent=format(score);$("resultCoins").textContent="250";$("resultGems").textContent=stars===3?"2":"1";$$(".star").forEach((s,i)=>s.classList.toggle("lit",i<stars));$("winModal").classList.add("open");haptic("heavy");beep(880,.18)}else{state.lives=Math.max(0,state.lives-1);$("loseScore").textContent=format(score);$("loseModal").classList.add("open");haptic("rigid");beep(150,.2)}syncTop();save()}
$("nextLevelBtn").onclick=()=>{closeModal("winModal");startLevel(state.level)};$("mapAfterWin").onclick=()=>{closeModal("winModal");showScreen("map")};$("retryBtn").onclick=()=>{closeModal("loseModal");startLevel(levelPlaying)};$("mapAfterLose").onclick=()=>{closeModal("loseModal");showScreen("map")};
$("shuffleBtn").onclick=()=>{if(busy)return;if((state.inventory.shuffle||0)<=0)return toast("Купите перемешивание в магазине");state.inventory.shuffle--;generateBoard();renderBoard(true);renderBoosters();save();toast("Поле перемешано")};
$("bombBtn").onclick=()=>toggleBooster("bomb");$("saladBtn").onclick=()=>toggleBooster("salad");$("extraBtn").onclick=()=>{if(busy)return;if((state.inventory.extra||0)<=0)return toast("Нет дополнительных ходов");state.inventory.extra--;moves+=5;renderBoard();save();toast("+5 ходов")};
function toggleBooster(k){if((state.inventory[k]||0)<=0)return toast("Бустер закончился");boosterMode=boosterMode===k?"":k;renderBoosters();$("gameMessage").textContent=boosterMode?"Выберите фишку":"Соберите комбинацию"}
function renderDaily(){const rewards=[["🪙","100"],["💎","1"],["🥗","×1"],["🪙","200"],["💎","2"],["🎁","Подарок"],["🛍️","Набор"]];$("dailyGrid").innerHTML=rewards.map((r,i)=>`<div class="day-card ${i+1<state.dailyDay?"claimed":i+1===state.dailyDay?"today":""}"><b>ДЕНЬ ${i+1}</b><div class="gift">${r[0]}</div><small>${r[1]}</small></div>`).join("");const today=new Date().toISOString().slice(0,10),claimed=state.dailyClaim===today;$("dailyClaimBtn").disabled=claimed;$("dailyClaimBtn").textContent=claimed?"Получено":"Получить"}
$("dailyClaimBtn").onclick=()=>{const today=new Date().toISOString().slice(0,10);if(state.dailyClaim===today)return;state.dailyClaim=today;state.coins+=100;state.inventory.salad=(state.inventory.salad||0)+1;state.dailyDay=state.dailyDay>=7?1:state.dailyDay+1;syncTop();renderDaily();toast("+100 монет и бустер")};
function renderTournament(){const users=[["🥑","Алексей",180000],["👩","Екатерина",250000],["👩🏻","Мария",120000]];users.forEach((u,i)=>{$(`podAvatar${i}`).textContent=u[0];$(`podName${i}`).textContent=u[1];$(`podScore${i}`).textContent=format(u[2])});$("yourTournamentScore").textContent=format(state.best);$("tournamentSeason").textContent=cfg.season?.name||"PP Challenge"}
const SHOP={shuffle:{icon:"🔀",title:"Перемешать",desc:"Новое поле",price:60},bomb:{icon:"💣",title:"Бомба",desc:"Удаляет область 3×3",price:80},salad:{icon:"🥗",title:"Радуга",desc:"Удаляет один продукт",price:120},extra:{icon:"🦶",title:"+5 ходов",desc:"Продолжить уровень",price:50}};
function renderShop(){$("shopItems").innerHTML=Object.entries(SHOP).map(([k,x])=>`<article class="shop-item"><div class="shop-icon">${x.icon}</div><b>${x.title}</b><p>${x.desc}</p><button class="price-btn" data-buy="${k}">🪙 ${x.price}</button></article>`).join("");$$('[data-buy]').forEach(b=>b.onclick=()=>buyItem(b.dataset.buy));syncTop()}
function buyItem(k){const x=SHOP[k];if(state.coins<x.price)return toast("Недостаточно монет");state.coins-=x.price;state.inventory[k]=(state.inventory[k]||0)+1;syncTop();toast(`${x.title}: +1`)}
$$(".shop-tabs button").forEach(b=>b.onclick=()=>{$$(".shop-tabs button").forEach(x=>x.classList.toggle("active",x===b));toast("Раздел магазина обновлён")});
$("buyPack199").onclick=()=>{if(state.coins<199)return toast("Недостаточно монет");state.coins-=199;state.lives=5;state.gems+=2;state.inventory.salad+=1;syncTop();toast("Набор здоровья получен")};
$("buyPack399").onclick=()=>{if(state.coins<399)return toast("Недостаточно монет");state.coins-=399;state.lives=5;state.gems+=5;for(const k of Object.keys(state.inventory))state.inventory[k]+=2;syncTop();toast("PRO-набор получен")};
window.addEventListener("storage",e=>{if(e.key===CFG_KEY){cfg=loadCfg();icons=cfg.icons?.length>=6?cfg.icons:DEFAULT_ICONS;iconMap=new Map(icons.map(x=>[x.id,x]));renderMap();toast("Настройки сезона обновлены")}});
const user=tg?.initDataUnsafe?.user;if(user){const name=[user.first_name,user.last_name].filter(Boolean).join(" ");$("profileName").textContent=name||"Игрок PP Balance";$("profileAvatar").textContent=(user.first_name||"И")[0].toUpperCase()}
syncTop();renderMap();renderDaily();renderTournament();renderShop();showScreen("map");
})();
